- name: Create build dir
  file:
    state: directory
    path: "{{ route53_build_dir }}"

- name: Create route53 template
  template:
    src: "{{ route53_template_src }}"
    dest: "{{ route53_template_dest_tmp }}"

- name: Cleanup template
  shell: "cat {{ route53_template_dest_tmp }} | python -m json.tool > {{ route53_template_dest }}"

- name: Remove temp template
  file: path={{ route53_template_dest_tmp }} state=absent

- name: create CloudFormation stack
  cloudformation:
    template: "{{ route53_template_dest }}"
    stack_name: "{{ route53_stack_name }}"
    region: "{{ region }}"
    tags: "{{ route53_tags }}"
    template_parameters:
      DNSName: "{{ route53_dns_name }}"
      HostedZone: "{{ route53_zone_name }}"
      TargetAddress: "{{ route53_target_address }}"
    security_token: "{{ ansible_security_token }}"
  register: cfstack

- debug: var=cfstack
